service: swappa-ipad-pro

provider:
  name: aws
  runtime: nodejs6.10
  timeout: 300
  memorySize: 256

  stage: dev
  region: us-east-1

  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "ses:SendEmail"
        - "ses:SendRawEmail"
        - "logs:CreateLogGroup"
        - "logs:CreateLogStream"
        - "logs:PutLogEvents"
        - "dynamodb:*"
      Resource: "*"

functions:
  capture:
    handler: index.capture
    events:
      - http:
          path: capture
          method: get
          cors: true
      - schedule: rate(5 minutes)
